fix: integer enum
oazapfts/oazapfts pull request #349
Opened 2022-12-07 23:48 UTC by trim21

fix case like this:

openapi type can be `number` or `integer`

```yaml
        state:
          title: CommentState
          example: 0
          enum:
            - 0
            - 1
            - 2
            - 5
            - 6
            - 7
          type: integer
          x-enumNames: [...]
          description: |-
```

close https://github.com/oazapfts/oazapfts/issues/348

there is no strandard way to set enum names in openapi 3.0.x but `x-enumNames` is common used, so this PR will require `x-enumNames` property as integer enum name in typescript Enum declare

2022-12-08 22:04 UTC, jonkoops requested changes
Can you add some tests to confirm this works?

2022-12-08 22:07 UTC, trim21 commented
can i update petstore.json and re-generate demo directly?

2022-12-08 22:12 UTC, trim21 commented
never mind, I find where tests files are

2022-12-09 11:58 UTC, trim21 commented
/ping

2022-12-14 16:08 UTC, trim21 commented
/ping

2022-12-21 08:48 UTC, trim21 commented
any progress？

2022-12-26 15:15 UTC, trim21 commented
/ping

2022-12-27 23:24 UTC, trim21 commented
@fgnass would you mind take a look at this pr? It has been weeks, I really hope to get some feedback

2022-12-28 11:53 UTC, fgnass commented
Sorry this took so long! I just added support for `x-enumNames` and `x-enum-varnames` as part of https://github.com/oazapfts/oazapfts/commit/8db31c274ab7dfb492066f2b00a8fbf7c3bd395f

2022-12-28 11:53 UTC, closed without merging